"""Test file writer - writes generated test cases to disk."""

from __future__ import annotations

from pathlib import Path

from .models import AgentConfig, TestCase, TestSuite


class TestWriter:
    """Writes generated test case files to disk."""

    def __init__(self, config: AgentConfig) -> None:
        self.config = config

    def write_suite(self, suite: TestSuite) -> list[Path]:
        """Write all test cases in a suite to disk."""
        output_dir = suite.output_directory or self._resolve_output_dir()
        output_dir.mkdir(parents=True, exist_ok=True)

        written_files: list[Path] = []

        for test_case in suite.test_cases:
            file_path = output_dir / f"{test_case.test_class_name}.swift"
            content = self._render_test_file(test_case)
            file_path.write_text(content, encoding="utf-8")
            written_files.append(file_path)

        return written_files

    def write_test_case(self, test_case: TestCase, output_dir: Path | None = None) -> Path:
        """Write a single test case to disk."""
        output_dir = output_dir or self._resolve_output_dir()
        output_dir.mkdir(parents=True, exist_ok=True)

        file_path = output_dir / f"{test_case.test_class_name}.swift"
        content = self._render_test_file(test_case)
        file_path.write_text(content, encoding="utf-8")

        return file_path

    def _resolve_output_dir(self) -> Path:
        """Resolve the output directory for test files."""
        if self.config.output_path:
            return Path(self.config.output_path).resolve()

        project_path = Path(self.config.project_path).resolve()

        # Try to find existing test directory
        common_test_dirs = [
            project_path / f"{project_path.name}Tests",
            project_path / "Tests",
            (
                project_path / f"{self.config.test_target_name}Tests"
                if self.config.test_target_name
                else None
            ),
        ]

        for test_dir in common_test_dirs:
            if test_dir and test_dir.exists():
                return test_dir

        # Default: create Tests directory in project root
        return project_path / "GeneratedTests"

    def _render_test_file(self, test_case: TestCase) -> str:
        """Render a complete test file from a test case."""
        parts: list[str] = []

        # File header
        parts.append("//")
        parts.append(f"//  {test_case.test_class_name}.swift")
        parts.append("//  Generated by iOS Test Generator Agent")
        parts.append("//")
        parts.append(f"//  Source: {test_case.source_file_path}")
        parts.append("//")
        parts.append("")

        # Imports
        for imp in test_case.imports:
            parts.append(f"import {imp}")
        parts.append("")

        # Check if the raw_source already contains a complete class
        # If it does, prefer using the raw source
        if self._is_complete_test_source(test_case.raw_source):
            parts.append(test_case.raw_source)
        else:
            # Build the test class manually
            parts.append(f"// MARK: - {test_case.test_class_name}")
            parts.append(f"class {test_case.test_class_name}: XCTestCase {{")
            parts.append("")

            # Properties section
            parts.append("    // MARK: - Properties")
            parts.append("")

            # Setup
            if test_case.setup_method:
                parts.append("")
                parts.append("    // MARK: - Setup & Teardown")
                parts.append("")
                # Indent the setup method properly
                for line in test_case.setup_method.split("\n"):
                    if line.strip():
                        parts.append(f"    {line.strip()}")
                    else:
                        parts.append("")
                parts.append("")

            # Teardown
            if test_case.teardown_method:
                for line in test_case.teardown_method.split("\n"):
                    if line.strip():
                        parts.append(f"    {line.strip()}")
                    else:
                        parts.append("")
                parts.append("")

            # Test methods
            if test_case.test_methods:
                parts.append("    // MARK: - Tests")
                parts.append("")
                for i, method in enumerate(test_case.test_methods):
                    for line in method.split("\n"):
                        if line.strip():
                            parts.append(f"    {line.strip()}")
                        else:
                            parts.append("")
                    if i < len(test_case.test_methods) - 1:
                        parts.append("")

            # Close class
            parts.append("}")

        parts.append("")  # Trailing newline
        return "\n".join(parts)

    def _is_complete_test_source(self, source: str) -> bool:
        """Check if the raw source is a complete, well-formed test class."""
        if not source:
            return False

        # Check for basic structure
        has_import = "import" in source
        has_class = "class" in source and "XCTestCase" in source
        has_test_func = "func test" in source

        return has_import and has_class and has_test_func
